spring:
  application:
    name: ebankify_security
    jwtSecret: Zm9vYmFyY29vbG9kZjY4ZGlvb3Bsd2FyZjNkZXVvY2lwdA==
    jwtExpirationMs: 3600000
  datasource:
    url: jdbc:postgresql://localhost:5432/ebankify_security
    username: root
    password: ;(.314Luiv./
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/main
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: ebankify-rest-api
      principal-name-val: "preferred_username"

server:
  port: 8081