server:
  port: 8081
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: mL6o2HdswC9rZdy1gOdOagDrHipdDlMQ
    key-store-type: PKCS12
    key-alias: ebankify

spring:
  application:
    name: ebankify_security
  datasource:
    url: jdbc:postgresql://localhost:5432/ebankify_security
    username: root
    password: ;(.314Luiv./
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/main
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: ebankify-rest-api
      principal-name-val: "email"

keycloak:
  realm: ebankify
  auth-server-url: http://localhost:8080/auth
  resource: spring-boot-client
  credentials:
    secret: mL6o2HdswC9rZdy1gOdOagDrHipdDlMQ
  bearer-only: true
  use-resource-role-mappings: true