spring:
  application:
    name: ebankify_security
    jwtSecret: Zm9vYmFyY29vbG9kZjY4ZGlvb3Bsd2FyZjNkZXVvY2lwdA==
    jwtExpirationMs: 3600000
  datasource:
    url: jdbc:postgresql://localhost:5432/ebankify_security
    username: root
    password: ;(.314Luiv./
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081